[[pages]]
path = "example_app/st-home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "example_app/st-partone.py"
name = "Part One"
icon = "ğŸ‘–"

[[pages]]
path = "example_app/st-parttwo.py"
name = "Part Two"
icon = ":shoe:"

[[pages]]
path = "example_app/st-partthree.py"
name = "Part Three"
icon = "ğŸ’°"

[[pages]]
path = "example_app/st-partfour.py"
name = "Part Four"
icon = "ğŸ’µ"